### ISSUE TITLE
Cannot start this exampel. Branch - v2.x

### ISSUE THREAD

**Issue by yu36yuqing** [dominhhai/koa-log4js-example#2]
Hi, thanks for your example. I got a question that have you ever start it?  I cannot successfully start it with following error.  Maybe the version for log4js is not correct, the format for this configuration seems belongs to v1.x.

3babel presets path = /Users/shangjian/Myself/nodejs/koa-log4js-example/node_modules/runkoa/node_modules
/Users/shangjian/Myself/nodejs/koa-log4js-example/node_modules/log4js/lib/configuration.js:44
        throw new Error(`Problem with log4js configuration: (${util.inspect(this.candidate, { depth: 5 })})` +
        ^

Error: Problem with log4js configuration: ({ appenders:
   [ { type: 'console' },
     { type: 'clustered',
       appenders:
        [ { type: 'dateFile',
            filename: 'startup.log',
            pattern: '-yyyy-MM-dd',
            category: 'startup' },
          { type: 'dateFile',
            filename: 'http.log',
            pattern: '-yyyy-MM-dd',
            category: 'http' },
          { type: 'file',
            filename: 'app.log',
            maxLogSize: 10485760,
            numBackups: 5 },
          { type: 'logLevelFilter',
            level: 'ERROR',
            appender: { type: 'file', filename: 'errors.log' } } ] } ] }) - must have a property "appenders" of type object.
    at tests.forEach (/Users/shangjian/Myself/nodejs/koa-log4js-example/node_modules/log4js/lib/configuration.js:44:15)
    at Array.forEach (<anonymous>)
    at Configuration.throwExceptionIf (/Users/shangjian/Myself/nodejs/koa-log4js-example/node_modules/log4js/lib/configuration.js:42:11)
    at new Configuration (/Users/shangjian/Myself/nodejs/koa-log4js-example/node_modules/log4js/lib/configuration.js:219:10)
    at Object.configure (/Users/shangjian/Myself/nodejs/koa-log4js-example/node_modules/log4js/lib/log4js.js:205:12)
    at Object.<anonymous> (/Users/shangjian/Myself/nodejs/koa-log4js-example/bin/www:26:7)
    at Module._compile (module.js:652:30)
    at loader (/Users/shangjian/Myself/nodejs/koa-log4js-example/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/shangjian/Myself/nodejs/koa-log4js-example/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at module.exports (/Users/shangjian/Myself/nodejs/koa-log4js-example/node_modules/runkoa/index.js:46:3)
    at Object.<anonymous> (/Users/shangjian/Myself/nodejs/koa-log4js-example/bin/run:4:18)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by dominhhai** [comment]
The log config file is changed! I will update later.

**Comment by dominhhai** [comment]
please use this config file:
https://github.com/dominhhai/koa-log4js-example/blob/master/log4js.json
